name: CI SonarCloud

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '11' }
      - name: Cache Maven deps
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Install Node
        uses: actions/setup-node@v4
        with: { 'node-version': '20' }
      - name: npm install & tests
        working-directory: front
        run: |
          npm ci && npm run test -- --watch=false --code-coverage --browsers=ChromeHeadless --no-sandbox
      - name: build & tests
        working-directory: back
        run: mvn clean verify
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.organization=raygriffon \
          -Dsonar.projectKey=RayGriffon_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD \
          -Dsonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml \
          -Dsonar.typescript.lcov.reportPaths=front/coverage/lcov.info