name: CI Tests & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      ### FRONT-END ###
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install front-end dependencies
        working-directory: front
        run: npm ci

      - name: Run front-end tests with coverage
        working-directory: front
        run: |
          npm run test -- --watch=false --code-coverage

      - name: Upload Angular coverage report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: front/coverage