name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_FRONT: bobapp-front
  IMAGE_BACK: bobapp-back
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Back-end - Run tests with Maven
        working-directory: back
        run: mvn clean install

      - name: Front-end - Install dependencies
        working-directory: front
        run: npm install

      - name: Front-end - Run build (if applicable)
        working-directory: front
        run: npm run build || true

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}

      - name: Build and push Front Docker image
        run: |
          docker build -t $REGISTRY/${{ env.DOCKER_USER }}/${{ env.IMAGE_FRONT }} ./front
          docker push $REGISTRY/${{ env.DOCKER_USER }}/${{ env.IMAGE_FRONT }}

      - name: Build and push Back Docker image
        run: |
          docker build -t $REGISTRY/${{ env.DOCKER_USER }}/${{ env.IMAGE_BACK }} ./back
          docker push $REGISTRY/${{ env.DOCKER_USER }}/${{ env.IMAGE_BACK }}
